# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-27 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='profile',
            field=models.IntegerField(default=0),
        ),
    ]
